---
# These tasks create the private ansible automation hub 
# credentials for managing execution environments and collections

# We need to create tokens for the synchronized namespaces
# We also may want to add a demo namespace to upload our own collections 

- name: Create a new token using username/password
  infra.ah_configuration.ah_token:
    ah_host: "{{ hubs[0].fqdn }}"
    ah_username: "admin"
    ah_password: "{{ aap_hub_admin_password_vault }}"
    state: present
    validate_certs: "{{ aap_validate_certs }}"
  register: result

- debug:
    var: result

- name: Extract the token
  ansible.builtin.set_fact:
    ah_container_token: "{{ result.ansible_facts.ah_token }}"