---
# add a list of credentials to aap

- name: "Add the galaxy/hub credentials to the Organization"
  ansible.builtin.include_tasks: "ensure_credential_to_org.yml"
  loop: "{{ org_galaxy }}"
  loop_control:
    loop_var: org



