---
# add a list of credentials to aap

- name: "Add the list of credentials to the Controller"
  ansible.builtin.include_tasks: "ensure_aap_credential.yml"
  loop: "{{ credentials }}"
  loop_control:
    loop_var: cred



