---
# This task creates the aap template from the list
# 

- name: "Ensure that {{ template.name }} is {{ template.state }}"
  ansible.controller.job_template:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    allow_simultaneous: "{{ template.allow_simultaneous | default(omit) }}"
    ask_credential_on_launch: "{{ template.ask_credential_on_launch | default(omit) }}"
    ask_diff_mode_on_launch: "{{ template.ask_diff_mode_on_launch | default(omit) }}"
    ask_execution_environment_on_launch: "{{ template.ask_execution_environment_on_launch | default(omit) }}"
    ask_forks_on_launch: "{{ template.ask_forks_on_launch | default(omit) }}"
    ask_instance_groups_on_launch: "{{ template.ask_instance_groups_on_launch | default(omit) }}"
    ask_inventory_on_launch: "{{ template.ask_inventory_on_launch | default(omit) }}"
    ask_job_slice_count_on_launch: "{{ template.ask_job_slice_count_on_launch | default(omit) }}"
    ask_job_type_on_launch: "{{ template.ask_job_type_on_launch | default(omit) }}"
    ask_labels_on_launch: "{{ template.ask_labels_on_launch | default(omit) }}"
    ask_limits_on_launch: "{{ template.ask_limits_on_launch | default(omit) }}"
    ask_scm_branch_on_launch: "{{ template.ask_scm_branch_on_launch | default(omit) }}"
    ask_skip_tags_on_launch: "{{ template.ask_skip_tags_on_launch | default(omit) }}"
    ask_tags_on_launch: "{{ template.ask_tags_on_launch | default(omit) }}"
    ask_timeout_on_launch: "{{ template.ask_timeout_on_launch | default(omit) }}"
    ask_variables_on_launch: "{{ template.ask_variables_on_launch | default(omit) }}"
    ask_verbosity_on_launch: "{{ template.ask_verbosity_on_launch | default(omit) }}"
    become_enabled: "{{ template.become_enabled | default(omit) }}"
    credentials: "{{ template.credentials }}"
    description: "{{ template.description | default(omit) }}"
    diff_mode: "{{ template.diff_mode | default(omit) }}"
    execution_environment: "{{ template.execution_environment | default('Default') }}"
    extra_vars: "{{ template.variables | default(omit) }}"
    force_handlers: "{{ template.force_handlers | default(omit) }}"
    forks: "{{ template.forks | default(omit) }}"
    instance_groups: "{{ template.instance_groups | default(omit) }}"
    inventory: "{{ template.inventory }}"
    job_slice_count: "{{ template.job_slice_count | default(omit) }}"
    job_tags: "{{ template.job_tags | default(omit) }}"
    job_type: "{{ template.job_type | default('run') }}"
    labels: "{{ template.labels | default(omit) }}"
    limit: "{{ template.limit | default(omit) }}"
    name: "{{ template.name }}"
    new_name: "{{ template.new_name | default(omit) }}"
    organization: "{{ template.organization | default('Default') }}"
    playbook: "{{ template.playbook | default('main.yml') }}"
    project: "{{ template.project }}"
    scm_branch: "{{ template.scm_branch | default(omit) }}"
    skip_tags: "{{ template.skip_tags | default(omit) }}"
    start_at_task: "{{ template.start_at_task | default(omit) }}"
    state: "{{ template.state | default('present') }}"
    survey_enabled: "{{ template.survey_enabled | default(omit) }}"
    survey_spec: "{{ template.survey_spec | default(omit) }}"
    timeout: "{{ template.timeout | default(omit) }}"
    use_fact_cache: "{{ template.use_fact_cache | default(omit) }}"
    validate_certs: "{{ aap_validate_certs }}"
    vault_credential: "{{ template.vault_credential | default(omit) }}"
    verbosity: "{{ template.verbosity | default(omit) }}"
    webhook_credential: "{{ template.webhook_credential | default(omit) }}"
    webhook_service: "{{ template.webhook_service | default(omit) }}"

  