---
# This task ensures an inventory status

- name: "Ensure the inventory {{ inventory.name }} is {{ inventory.state }}"
  ansible.controller.inventory:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    description: "{{ inventory.description | default(omit) }}"
    host_filter: "{{ inventory.host_filter | default(omit) }}"
    input_inventories: "{{ inventory.input_inventories | default(omit) }}"
    instance_groups: "{{ inventory.instance_groups | default(omit) }}"
    kind: "{{ inventory.kind | default(omit) }}"
    name: "{{ inventory.name }}"
    new_name: "{{ inventory.new_name | default(omit) }}"
    organization: "{{ inventory.organization | default('Default') }}"
    state: "{{ inventory.state | default(present) }}"
    validate_certs: "{{ aap_validate_certs }}"
    variables: "{{ inventory.variables | default(omit) }}"

