---
# This adds a credential to the aap controller configuration

- name: "Add the credential {{ cred.name }}"
  ansible.controller.credential:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    credential_type: "{{ cred.credential_type }}"
    name: "{{ cred.name }}"
    organization: "{{ cred.organization | default('Default') }}"
    description: "{{ cred.description | default(omit) }}"
    inputs:
      username: "{{ cred.inputs.username | default(omit) }}"
      password: "{{ cred.inputs.password | default(omit) }}"
      ssh_key_data: "{{ cred.inputs.ssh_key_data | default(omit) }}" #ssh private key data - use lookup
      ssh_key_unlock: "{{ cred.inputs.ssh_key_unlock | default(omit) }}" # password for ssh key
      ssh_public_key_data: "{{ cred.inputs.ssh_public_key_data | default(omit) }}" #ssh private key data - use lookup
      become_method: "{{ cred.inputs.become_method | default(omit) }}"
      become_username: "{{ cred.inputs.become_username | default(omit) }}"
      become_password: "{{ cred.inputs.become_password | default(omit) }}"
      vault_password: "{{ cred.inputs.vault_password | default(omit) }}"
      vault_id: "{{ cred.inputs.vault_id | default(omit) }}"
      url: "{{ cred.inputs.url | default(omit) }}" # url for content for galaxy credential
      auth_url: "{{ cred.inputs.auth_url | default(omit) }}"  # use with Galaxy credential
      token: "{{ cred.inputs.token | default(omit) }}" # access token for galaxy credential
      authorize: "{{ cred.inputs.authorize | default(omit) }}" # for network
      authorize_password: "{{ cred.inputs.authorize_password | default(omit) }}" # for network
      security_token: "{{ cred.inputs.security_token | default(omit) }}" # For AWS
      api_key: "{{ cred.inputs.api_key | default(omit) }}" #for RAX instead of password
      subscription: "{{ cred.inputs.subscription | default(omit) }}" # for AzureRM
      client: "{{ cred.inputs.client | default(omit) }}" # for AzureRM
      tenant: "{{ cred.inputs.tenant | default(omit) }}" # for AzureRM
      secret: "{{ cred.inputs.secret | default(omit) }}" # for AzureRM
      cloud_environment: "{{ cred.inputs.cloud_environment | default(omit) }}" # for AzureRM with Azure GovCloud
      host: "{{ cred.inputs.host | default(omit) }}" # for multiple, including OpenStack
      project: "{{ cred.inputs.project | default(omit) }}" # OpenStack
      project_domain: "{{ cred.inputs.project_domain | default(omit) }}" # OpenStack
      domain: "{{ cred.inputs.domain | default(omit) }}" # OpenStack
      region: "{{ cred.inputs.region | default(omit) }}" # OpenStack
      verify_ssl:  "{{ cred.inputs.verify_ssl | default(omit) }}"  # OpenStack for credential endpoint rather than controller
      access_key: "{{ cred.inputs.access_key | default(omit) }}" #for AWS instead of username
      secret_key: "{{ cred.inputs.secret_key | default(omit) }}" #for AWS instead of password
      bearer_token: "{{ cred.inputs.bearer_token | default(omit) }}" # for kube/openshift
      oauth_token: "{{ cred.inputs.oauth_token | default(omit) }}" # for Ansible Automation controller    
      gpg_public_key: "{{ cred.inputs.gpg_public_key | default(omit) }}"
    new_name: "{{ cred.new_name | default(omit) }}"
    user: "{{ cred.user | default(omit) }}"
    team: "{{ cred.team | default(omit) }}"
    state: "{{ cred.state | default('present') }}"
    validate_certs: "{{ cred.validate_certs | default('false') }}"

#######################################################################################################################
# MANAGED TYPES
# Documentation generated from https://github.com/ansible/awx/blob/devel/awx/main/models/credential/__init__.py
# You can specify kind as the credential type or namespace form
#
# Name (kind)             namspace (kind short)  Inputs Field            Type        Info
# -------------------------------------------------------------------------------------------------
# Machine                 ssh                    username                string      Username
#                                                password                string      Password
#                                                ssh_key_data            string      ssh Private Key
#                                                ssh_key_unlock          string      ssh Private Key password
#                                                ssh_public_key_data     string      ssh Public Key
#                                                become_method           string      Privilege Escalation method
#                                                become_username         string      Privilege Escalation username
#                                                become_password         string      Privilege Escalation password
#
# Source Control          scm                    username                string      Username
#                                                password                string      Password
#                                                ssh_key_data            string      ssh Private Key
#                                                ssh_key_unlock          string      ssh Private Key password
#
# Vault                   vault                  vault_password          string      Vault password (required)
#                                                vault_id                string      Vault identity
#
# Network                 net                    username                string      Username (required)
#                                                password                string      Password
#                                                ssh_key_data            string      ssh Private Key
#                                                ssh_key_unlock          string      ssh Private Key password
#                                                authorize               string      Authorize 
#                                                authorize_password      string      Autorize password (requires authorize)
#
# Amazon Web Services     aws                    username                string      Access Key (required)
#                                                password                string      Secret Key (required)
#                                                security_token          string      STS Token
#
# OpenStack               openstack              username                string      Username (required)
#                                                password                string      Password (required)
#                                                host                    string      Host Authentication URL (required) (e.g. https://openstack.example.ca/v2.0/)
#                                                project                 string      Project Tenant Name (required)
#                                                project_domain_name     string      Project Domain Name
#                                                domain                  string      Domain Name (only needed for Keystone v3 authentication URLs)
#                                                region                  string      Region Name (for some cloud providers e.g. OVH requires this)
#                                                verify_ssl              boolean     default == true
#
# VMware vCenter          vmware                 username                string      Username (required)
#                                                password                string      Password (required)
#                                                host                    string      vCenter Host (required) (ip or hostname)
#                                                
# Red Hat Satellite 6     satellite6             username                string      Username (required)
#                                                password                string      Password (required)
#                                                host                    string      Satellite URL (required) (e.g. https://satellite.example.ca)
#
# Google Compute Engine   gce                    username                string      Service Account Email Address (required)
#                                                project                 string      Project ID (e.g. project-id-000)
#                                                ssh_key_data            string      RSA Private Key (required) (e.g. associated with the service account email)
#
# Microsoft Azure Resource Manager   azure_rm    subscription            string      Subscription ID (required)
#                                                username                string      Username 
#                                                password                string      Password
#                                                client                  string      Client ID
#                                                tenant                  string      Tenant ID
#                                                secret                  string      Client Secret
#                                                cloud_environment       string      Environment variable AZURE_CLOUD_ENVIRONMENT when using Azure GovCloud or Azure stack.
#
# GitHub Personal Access Token   github_token    token                   string      Token (required) - This token needs to come from your profile settings in GitHub
#
# GitLab Personal Access Token   gitlab_token    token                   string      Token (required) - This token needs to come from your profile settings in GitLab
#
# Insights                insights               username                string      Username (required) 
#                                                password                string      Password (required)
#
# Red Hat Ansible Automation Platform 
#                         controller             username                string      Username (antirequisite oauth_token)
#                                                password                string      Password 
#                                                host                    string      Base URL of the controller (required)
#                                                oauth_token             string      An OAuth token to use to authenticate with.This should not be set if username/password are being used.
#                                                verify_ssl              boolean
#
# OpenShift or Kubernetes API Bearer Token
#                      kubernetes_bearer_token   host                    string      Openshift or Kubernetes endpoint url (required)
#                                                bearer_token            string      API authentication bearer token (required)
#                                                verify_ssl              boolean    
#                                                ssl_ca_cert             string      Certificate authority data
#
# Container Registry   registry                  username                string      Username
#                                                password                string      Password 
#                                                host                    string      Authentication URL of the registry (required)
#                                                verify_ssl              boolean     default == true
#
# Ansible Galaxy/Automation Hub API Token
#                      galaxy_api_token          url                     string      Galaxy Server URL (required) (e.g. https://ah1.example.ca/api/galaxy/content/rh-certified/)
#                                                auth_url                string      Auth Server URL              (e.g. https://ah1.example.ca/api/)
#                                                token                   string      API Token 
#
# GPG Public Key       gpg_public_key            gpg_public_key          string      GPG Public Key used to validate content signatures (required)
#
#
# END OF MANAGED TYPES
#######################################################################################################################