---
# Build and upload an ee
- name: "Create the base directory"
  ansible.builtin.file:
    path: "{{ ee.git_dest }}"
    state: directory

- name: "Clone the git repo for the ee"
  ansible.builtin.git:
    repo: "{{ ee.git_repo }}"
    dest: "{{ ee.git_dest }}/{{ ee.name }}"
    clone: "{{ ee.git_clone | default(omit) }}"
    force: "{{ ee.git_force | default(omit) }}"

- name: "Add ansible.cfg template"
  ansible.builtin.template:
    src: "../templates/builder_ansible.cfg.j2"
    dest: "{{ ee.git_dest }}/{{ ee.name }}/ansible.cfg"

- name: "Add our ca certficate to the image"
  ansible.builtin.copy:
    src: "/etc/ipa/ca.crt"
    dest: "{{ ee.git_dest }}/{{ ee.name }}/context"
    remote_src: true

- name: "Build the ee on the target os"
  ansible.builtin.command: "ansible-builder build -t {{ ee.name }} --prune-images"
  args:
    chdir: "{{ ee.git_dest }}/{{ ee.name }}"

- name: "Push the finished container to the hub"
  containers.podman.podman_image:
    name: "{{ ee.name }}"
    push: yes
    username: "{{ private_hub_username }}"
    password: "{{ private_hub_password }}"
    push_args:
      dest: "{{ hubs[0].fqdn }}"
      remove_signatures: true
  
