---
# This play creates an individual content view from specified paramters
- name: "Create the content view - {{ cv.name }}"
  redhat.satellite.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_initial_organization }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ cv.name }}"
    description: "{{ cv.desc }}"
    repositories: "{{ cv.repositories }}"
    state: "{{ cv.state | default(omit) }}"

# Add the filters
- name: "Add the filters to the Content View - {{ cv.name }}"
  include_tasks: create_cv_filter.yml
  loop: "{{ cv.filters }}"
  loop_control:
    loop_var: cvf
  when: "cv.filters is defined"
